version: '3.4'

services:
  webapi:
    environment:
      - "ASPNETCORE_ENVIRONMENT=Development"
      - "SpaBaseUrl=http://clientapp:4200"

  clientapp:
    image: ${DOCKER_REGISTRY-}clientapp
    build:
      context: src/WebAPI/ClientApp
      dockerfile: Dockerfile
    depends_on:
      - webapi
    restart: on-failure

  db:
    ports:
      - "1433:1433"
